general.import = ["~/.config/omarchy/current/theme/alacritty.toml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 9

[window]
padding.x = 14
padding.y = 14
opacity = 0.8
blur = true          # does not work in omarchy
decorations = "None"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]
