# Theme
ZSH_THEME="amuse"

# zoxide
export ZOXIDE_CMD_OVERRIDE='cd'

# Oh my zsh plugins
plugins=(git poetry zsh-syntax-highlighting zsh-autosuggestions zsh-navigation-tools zoxide eza)
# Fastfetch
if [ $SHLVL -eq 1 ]; then
    fastfetch
fi

# Yazy
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}
bindkey -s '^e' 'y\n'

# fnm
FNM_PATH="/home/leopazes/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "`fnm env`"
fi


# envs for zsh
source ~/.local/share/omarchy/default/bash/envs
